// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Postmizan;

#nullable disable

namespace Postmizan.Migrations
{
    [DbContext(typeof(JsonContext))]
    partial class JsonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Postmizan.JsonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeleteJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GetJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PutJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JsonDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
